# -*- coding: utf-8 -*-
"""Imersão_Python_Alura.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H5tG-5ohgpn7nB4hiVm3o1SI-McVV3gC

Aula 2 - 260324
"""

import pandas as pd

df_principal = pd.read_excel("/Alura Imersão Python - Tabela de ações-executado-260324.xlsx", sheet_name="Principal")
df_principal





df_principal.head(10)

df_total_acoes = pd.read_excel("/Alura Imersão Python - Tabela de ações-executado-260324.xlsx", sheet_name="Total_de_acoes")
df_total_acoes

df_ticker = pd.read_excel("/Alura Imersão Python - Tabela de ações-executado-260324.xlsx", sheet_name="Ticker")
df_ticker

df_ChatGPT = pd.read_excel("/Alura Imersão Python - Tabela de ações-executado-260324.xlsx", sheet_name="ChatGPT")
df_ChatGPT

"""# Nova seção"""