# -*- coding: utf-8 -*-
"""PyDica #7 | O que são e quando usar Decoradores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IxrpFqph2j15vbS0rJg-rCo_wdLOcbFz

# PyDica #7 | O que são e quando usar Decoradores...

Você já se deparou com aqueles @ misteriosos em um código Python e ficou se perguntando o que eram? O que eles fazem? Onde dormem? Do que se alimentam?!



Calma jovem Pythonista! A Python Academy desvenda esse mistério pra você 😉



Esses são os Decoradores em ação!



Eles são uma forma estilosa e poderosa de adicionar ou modificar funcionalidades em funções ou métodos, sem ter que mexer no código original!



Vamos começar com um exemplo simples:
"""

def meu_decorador(funcao):
  def wrapper():
    print("Algo acontecendo antes da função.")
    funcao()
    print("Algo acontecendo depois da função.")
  return wrapper

@meu_decorador
def diga_ola():
    print("Olá!")

diga_ola()

"""Quando chamamos diga_ola(), estamos, na verdade, chamando wrapper(), graças à magia do @meu_decorador!



Mas não paramos por aqui!



Imagine que você queira um decorador que meça o tempo de execução de uma função:
"""



import time

def temporizador(funcao):
    def wrapper(*args, **kwargs):
      inicio = time.perf_counter()
      resultado = funcao(*args, **kwargs)
      fim = time.perf_counter()
      print(f"Tempo: {fim - inicio:.2f}s")
      return resultado
    return wrapper

@temporizador
def demora(segundos):
  time.sleep(segundos)

demora(2)

"""Ao executar esse código, veremos o tempo de execução do código!
E tem mais!

E se quiséssemos um decorador que fizesse log de quando uma função é chamada?
"""

def logger(funcao):
    def wrapper(*args, **kwargs):
        print("Logger:")
        print(f"\tArgs: {args}")
        print(f"\tKwargs: {kwargs}")
        return funcao(*args, **kwargs)
    return wrapper

@logger
def saudacao(nome, idade=None):
    return f"Olá {nome}! Você tem {idade} anos."

saudacao("Ana", idade=30)

"""Obteríamos a seguinte saída, logando todos os parâmetros da chamada da função, olha que incrível!

Daí nasceu o decorator, que nada mais é que um método para envolver uma função, modificando seu comportamento.

Para explicar melhor, veja o código abaixo:
"""

def decorator(funcao):
    def wrapper():
        print ("Estou antes da execução da função passada como argumento")
        funcao()
        print ("Estou depois da execução da função passada como argumento")

    return wrapper

def outra_funcao():
    print ("Sou um belo argumento!")

funcao_decorada = decorator(outra_funcao)
funcao_decorada()

"""Dessa forma, conseguimos adicionar qualquer comportamento antes e depois da execução de uma função qualquer!

Vamos fazer agora um exemplo mais útil, algo que todo mundo que desenvolve software teve que fazer alguma vez vida: calcular o tempo de execução de determinada função!

"""

import time

# Define nosso decorator
def calcula_duracao(funcao):
    def wrapper():
        # Calcula o tempo de execução
        tempo_inicial = time.time()
        funcao()
        tempo_final = time.time()

        # Formata a mensagem que será mostrada na tela
        print("[{funcao}] Tempo total de execução: {tempo_total}".format(
            funcao=funcao.__name__,
            tempo_total=str(tempo_final - tempo_inicial))
        )

    return wrapper

# Decora a função com o decorator
@calcula_duracao
def main():
    for n in range(0, 10000000):
        pass

# Executa a função main
main()

"""Nossa função principal tem apenas um loop que não faz nada, apenas itera n de 0 à 10000000, o que dura um certo tempo.

Marcamos o tempo de início e de término da execução com o módulo time e então subtraímos o final pelo inicial, dando o tempo total de execuções.

A saída será (o tempo de execução depende da sua máquina):
"""

# Vamos ver agora um exemplo real de utilização de Decorators!

"""Exemplo Real: Restringindo o Acesso em uma Aplicação Flask
Para quem não conhece, Flask é um framework web minimalista, muito simples de utilizar e bem divertido!

Está curtindo esse conteúdo?

Bom, quando desenvolvemos sistemas para web, nós sempre nos preocupamos com o controle de acesso a determinadas páginas.

Por exemplo, não queremos que usuários não autorizados acessem a URL /admin/. Para isso, uma abordagem seria incluir a verificação de usuários no corpo de toda função que trata requisições.
Exemplo (utilizando Flask):
"""

pip install flask==2.0.2

from flask import render_template

@app.route('/exemplo')
def exemplo:
    return render_template('exemplo.html')

from flask_foo import Foo

foo = Foo()

app = Flask(__name__)
app.config.update(
    FOO_BAR='baz',
    FOO_SPAM='eggs',
)

foo.init_app(app)

@app.route('/admin')
def admin_index():
    # Verifica se session['logado'] já foi setado
    if ('logado' not in session):
        return redirect('index')

    # Caso usuário esteja logado, renderiza a página /admin/index.html
    return render_template('/admin/index.html')

"""O problema dessa abordagem é que teremos que repetir a operação de verificar se o usuário está logado em toda requisição para /admin/*.

Isso gera código duplicado em todas essas funções. Sem contar que qualquer erro no “copia e cola” desse código pode estar expondo uma URL para qualquer usuário. Teeeenso! :hushed:

Para evitar esse tipo de problema, podemos criar um decorator que verifica se o usuário que está requisitando aquela página já efetuou o login ou não da seguinte forma:
"""

# Decorator
def requer_autenticacao(f):
    @wraps(f)
    def funcao_decorada(*args, **kwargs):
        # Verifica session['logado']
        if ('logado' not in session):
            # Retorna para a URL de login caso o usuário não esteja logado
            return redirect(url_for('index'))

        return f(*args, **kwargs)
    return funcao_decorada

"""Para utilizar esse decorator, precisamos apenas incluí-lo nas funções que queremos restringir o acesso. Exemplo:"""

# Olha quem tá aqui... Outro decorator :D
@app.route('/admin/dashboard')
@requer_autenticacao
def admin_dashboard():
    # Renderiza o template dashboard.html
    return render_template('admin/dashboard.html')