# -*- coding: utf-8 -*-
"""DESAFIO-PYTHON-20240220-XPEIGTI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lCyVT4vMrkXWYdr8_S423QxJfzx8vR7f

# Eduardo Miranda
eduardo.dpm@gmail.com

https://linkedin.com/in/eduardopmiranda

# Tipos de dados Python
📌 O material a seguir foi traduzido de [python-course.eu](https://python-course.eu/)

| Tipo | Categoria | Exemplo|
|:--------|:--------:|:--------:|
| **Bool** | | *True*, *False* |
| **Int** | Número | 20 |
| **Float** | Número | 35.75 |
| **complex** | Número | 1+3j |
| **String** | Sequência | "Python" |
| **List** | Sequência | [2, "a", 5.7] |
| **Tuple** | Sequência | (3, 4.5, "n") |
| **Set** | | {2, 4, 6} |
| **Dict** | | {"Treinamento":"Preparação de Dados com Python", "Data": "07/12/2022"} |

Existem diferentes maneiras de definir strings em Python:

```python
s = 'Sou uma string entre aspas simples.'
s2 = "Sou outra string, mas estou entre aspas duplas."
```

Ambos `s` e `s2` do exemplo anterior são variáveis que fazem referência a objetos string. Podemos ver que as strings literais podem ser colocadas entre aspas simples (') ou aspas duplas (").

```python
s3 = 'Não importa!'
```

E se quisermos criar um texto contendo aspas simples ou aspas duplas? Nestes casos teremos que escapar de aspas dentro de uma string.

```python
txt = "Ele disse: \"Não importa, se você colocar uma string entre aspas simples ou duplas!\""
print(txt)
```
"""

s = "XP Educaca'o 2024"

print(s)

"""Uma string em Python consiste em uma série ou sequência de caracteres — letras, números e caracteres especiais. Strings podem ser subscritas ou indexadas. Semelhante a C, o primeiro caractere de uma string tem o índice 0.

```python
s = "Hello World"
s[0]
```
"""

#    0123456789
s = "Ola mundo 2024"
print(s[4:9])

resultado = s.split()

resultado[2]

s = 123

print(s)

type(s)

"""# 🗃️ ```Collections``` no Python

Coleções em Python são contêineres usados para armazenar dados e são comumente conhecidos como estruturas de dados, como ```listas```, ```tuplas```, ```sets```, ```dicionários```, etc. Além disso, o Python possui um módulo de coleções integrado que fornece estruturas de dados adicionais para coleções de dados.

## Listas
As listas são usadas para armazenar vários itens em uma única variável. As listas são um dos 4 tipos de dados internos do Python usados para armazenar coleções de dados.

- Os itens da lista são indexados, o primeiro item tem índice ```[0]```, o segundo item tem índice ```[1]``` etc.
- Os itens da lista são ordenados, alteráveis (mutáveis) e permitem valores duplicados.
  - Quando dizemos que as listas são ordenadas, significa que os itens têm uma ordem definida, e essa ordem não será alterada. Se você adicionar novos itens a uma lista, os novos itens serão colocados no final da lista.
  - A lista é mutável, o que significa que podemos alterar, adicionar e remover itens em uma lista após ela ter sido criada.
  - Como as listas são indexadas, as listas podem ter itens com o mesmo valor.
"""

#                  0          1         2           3        4
#                 -5         -4        -3          -2       -1
lista_compras = ["arroz", "feijao", "macarrao", "acucar", "batata"]

print(lista_compras[0:-1])

lista_compras.append("leite")

print(lista_compras)

del lista_compras[0]

print(lista_compras)

lista_compras[1] = "Macarrao"

print(lista_compras)

lista_maluca = [123, "arroz", 1+3j, ["python"] ]

print(lista_maluca[3][0])

"""## 📚 Exercício: Listas

1. Escreva um programa Python para elevar ao quadrado todos os itens da **lista** ```[2, 3, 4, 5, 6, 7]```.

2. Escreva um programa Python para imprimir na tela apenas os elementos pares da lista ```[ 766, 57, 121, 4, 897, 1212, 87237, 1]```

3. Escreva um programa em Python para:
  - Converter uma string em lista separando a string pelo caractere espaço;
  - Selecionar as palavras onde o primeiro e o último caractere são  iguais;
  - Selecionar as palavras que possuem 2 ou mais caracteres.

**String**:
*At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.*
"""

lista = [2, 3, 4, 5, 6, 7]

 for elemento in lista:
  print(elemento, elemento ** 2)

lista = [2, 3, 4, 5, 6, 7]
lista_quadradro = [ i**2 for i in lista ]

lista_quadradro

lista = [ 766, 57, 121, 4, 897, 1212, 87237, 1]

for elemento in lista:
  if elemento % 2 == 0 :
    print(elemento)

lista = [766, 57, 121, 4, 897, 1212, 87237, 1]

pares = [elemento for elemento in lista if elemento % 2 == 0]

print(pares)

"""---
## Dicionários
Os dicionários Python nos permitem associar um valor a uma chave única e, em seguida, acessar rapidamente esse valor. É uma boa ideia usá-los sempre que quisermos encontrar (procurar) um determinado objeto Python. Também podemos usar listas para esse escopo, mas elas são muito mais lentas que os dicionários.

Essa velocidade se deve ao fato de que as chaves do dicionário são ```hashable```. Todo objeto imutável em Python é **hash**, então podemos passá-lo para a função ```hash()```, que retornará o valor de **hash** desse objeto. Esses valores são usados para pesquisar um valor associado à sua chave exclusiva.

### Quando utilizar dicionários?

- **Você deseja armazenar objetos e dados usando nomes, não apenas posições ou números de índice**. Se você deseja armazenar elementos para que possa recuperá-los por seu número de índice, use uma lista. Observe que você pode usar números inteiros como chaves de índice, mas isso não é exatamente o mesmo que armazenar dados em uma estrutura de lista, que é otimizada para ações como adicionar ao final da lista. (Dicionários, como você verá, não têm elemento "fim" ou "início" como tal.)
- **Você precisa encontrar dados e objetos rapidamente pelo nome**. Os dicionários são otimizados para que as pesquisas de chaves sejam quase sempre em tempo constante, independentemente do tamanho do dicionário. Você também pode encontrar um elemento em uma lista por sua posição em tempo constante, mas não pode procurar um elemento específico rapidamente - você precisa percorrer uma lista para encontrar uma coisa específica se não souber sua posição.
- **A ordem dos elementos não é tão importante quanto sua presença** ⚠️. Se a ordem dos elementos importa mais do que se um determinado elemento existe ou não na coleção, use uma lista. Além disso, como você notará abaixo, embora os dicionários preservem a ordem em que esses elementos são inseridos, isso não é o mesmo que poder usar ```seek()``` para buscar rapidamenteo *enésimo* elemento .

⚠️ A partir da versão ```3.7``` do Python, os dicionários são ordenados. No Python ```3.6``` e anteriores, os dicionários não são ordenados. Quando dizemos que os dicionários estão ordenados, significa que os itens têm uma ordem definida, e essa ordem não será alterada.
"""

dicionario = dict()

dicionario = {}

type(dicionario)

dicionario[12346578912] = "Eduardo Miranda"

print(dicionario)

dicionario[98765432185] = "Patricia Miranda"

print(dicionario)

print( dicionario )

dicionario[12346578912] = {"nome":"Eduardo", "e-mail":"eduardo.dpm@gmail.com", "cidade":"Sao Paulo"}

print( dicionario )

print( dicionario[12346578912]['e-mail'] )

"""## 📚 Exercício: Dicionários

1. Escreva um programa Python para gerar e imprimir um dicionário que contenha um número (entre 1 e ```n```) no formato (x, x*x). Para ```n = 5``` o resultado esperado é ```{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}```

2. No dicionário a seguir, imprima na tela a nota de Português da Patrícia.

```json
sampleDict = {
    "classe": {
        "estudantes": {
            "Eduardo": {
                "Matemática": 70,
                "Português": 80
            },
            "Patrícia": {
                "Matemática": 50,
                "Português": 90
            },
            "Mayara": {
                "Matemática": 98,
                "Português": 89
            }
        },
        "turno": "Manhã"
    }
}
```

6. A partir do dicionário de notas a seguir, imprima na tela a disciplina de menor nota.

```json
notas = {
    "Português": 9,
    "Matemática": 7,
    "Geografia": 8,
    "Filosofia":8,
    "Biologia":4,
    "Química": 9
}
```
"""

dicionario = {}
n = 5

for i in range(1,n+1):
  dicionario[i] = i**2

dicionario

# Dict comprehension
n = 5
dicionario2 = {  i : i**2 for i in range(1, n + 1) }

dicionario2

"""Baseado no Código 10, seja y_true os valores que devem ser previstos a partir de um modelo de aprendizado de máquinas e y_pred os valores que de fato foram previstos por esse modelo. O que o comando np.sqrt(((y_true-y_pred)**2).mean()) irá retornar?
Grupo de escolhas da pergunta

A raiz quadrada do erro quadrático médio do modelo.

A média do erro absoluto do modelo.

A taxa de falsos positivos do modelo.

O erro quadrático médio do modelo.
"""

import numpy as np
y_true = np.array([1., 2., 1.])
y_pred = np.array([1.1, 1.98, 1.05])

np.sqrt(((y_true - y_pred)**2).mean())

((1 - 1.1)**2)

import pandas as pd
df_players = pd.read_csv('https://datasets-aulas.s3.amazonaws.com/Players.csv')
df_players

"""## 📚 Exercício: Explore os dados da Tesla utilizando os seguintes métodos e propriedades

- [pandas.DataFrame.dtypes](https://pandas.pydata.org/docs/user_guide/basics.html#dtypes)
- [pandas.DataFrame.info()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html)
- [pandas.DataFrame.describe()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html)
- [pandas.DataFrame.head()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html)
- [pandas.DataFrame.tail()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html#pandas.DataFrame.tail)
- [pandas.DataFrame.index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.index.html)
- [pandas.DataFrame.columns](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html)
- [pandas.DataFrame.shape](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shape.html)
- [pandas.DataFrame.size](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.size.html)
- [pandas.DataFrame.count()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.count.html)
- [pandas.DataFrame.max()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.max.html)
- [pandas.DataFrame.min()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.min.html)
- [pandas.DataFrame.mean()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html)
- [pandas.DataFrame.std()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.std.html)
- [pandas.DataFrame.median()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.median.html)



**Download**: [TSLA.csv](https://drive.google.com/file/d/1PkYUb3fTxzM0T5Lt5tq6OqroKfIw3mte/view?usp=sharing)
"""

df_players.median()

"""---
# 🐼 Python Pandas

Pandas é uma ferramenta de análise e manipulação de dados de código aberto, rápida, poderosa, flexível e fácil de usar, construído sobre a linguagem de programação Python.
    
Em 2008, o desenvolvimento de pandas começou na AQR Capital Management. No final de 2009, ele era de código aberto e hoje é ativamente apoiado por uma comunidade de indivíduos com ideias semelhantes em todo o mundo que contribuem com seu valioso tempo e energia para ajudar a tornar os pandas de código aberto possíveis.

— Fonte: https://pandas.pydata.org/about/

## Series
*Uma série é um objeto unidimensional semelhante a uma matriz contendo uma sequência de valores (de tipos semelhantes aos tipos NumPy) e uma matriz associada de rótulos de dados, chamada de índice.*

— Livro: [Python for Data Analysis Data Wrangling with Pandas, NumPy, and IPython](https://www.amazon.com.br/Python-Data-Analysis-Wes-Mckinney/dp/1491957662)

## DataFrame
*Um DataFrame representa uma tabela retangular de dados e contém uma coleção ordenada de colunas, cada uma das quais pode ser um tipo de valor diferente (numérico, string,booleano, etc). O DataFrame tem um índice de linha e coluna; pode ser pensado como um dict de Series todos compartilhando o mesmo índice. Sob o capô, os dados são armazenados como um ou mais blocos bidimensionais em vez de uma lista, dict ou alguma outra coleção de matrizes unidimensionais.*

— Livro: [Python for Data Analysis Data Wrangling with Pandas, NumPy, and IPython](https://www.amazon.com.br/Python-Data-Analysis-Wes-Mckinney/dp/1491957662)
"""

import pandas as pd

# Criação de um novo dicionário do Python onde o valor para cada chave é uma lista de mesmo tamanho.

dados = {
    'ano'    : [ 2021, 2021, 2021, 2022, 2022],
    'mês'    : [ 'Outubro', 'Novembro', 'Dezembro', 'Janeiro', 'Fevereiro'],
    'volume' : [ 156.6, 96.8, 167.6, 378.6, 69.2]
}

# Um Dataframe está sendo criado a partir da lista criada anteriormente. E, diferente do exemplo da Série,
# onde a chave havia se tornado o índice, aqui as chaves do dicionário se tornaram as colunas do Dataframe

dframe = pd.DataFrame( dados )

dframe

dframe[ dframe['volume'] > 120 ]

"""## Métodos do pacote Pandas para importação de dados

Existem vários formatos de arquivos para armazenamento de dados: .csv, .json, .xlsx etc. e que podem ser armazenado em locais diferentes, em sua máquina local ou às vezes online. Nesta seção, você aprenderá como carregar um conjunto de dados no Jupyter Notebook.

- [pandas.read_excel()](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html)
- [pandas.read_csv()](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)
- [pandas.read_table()](https://pandas.pydata.org/docs/reference/api/pandas.read_table.html)
- [pandas.read_sql()](https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html)
- [pandas.read_json()](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html)
- [pandas.read_html()](https://pandas.pydata.org/docs/reference/api/pandas.read_html.html)
"""

import pandas as pd
tables = pd.read_html("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")

tables[0]

dfSP500 = tables[0]
dataFundacaoMaisAntigo = dfSP500['Founded'].min()

dataFundacaoMaisAntigo

dfSP500[ dfSP500['Founded'] == dataFundacaoMaisAntigo ]

dfSP500.sort_values( by = 'Founded', ascending=False).tail(5)

import pandas as pd
dfTSLA = pd.read_csv('https://datasets-aulas.s3.amazonaws.com/Dados+de+cota%C3%A7%C3%A3o+das+empresas+americanas/TSLA.csv')
dfTSLA